image: alpine:latest

services:
  - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    
stages:
    - validate
    - build

before_script:
    - apk add build-base
    - apk add docker
    - apk add ansible
    - ansible-galaxy install amine7777.packer
    - ansible-playbook install_packer.yml

########## CENTOS
validate:centos:
    stage: 'validate'
    script:
        - packer validate templates/docker/template-centos.json
    only:
        changes:
            - scripts/centos.sh
            - templates/docker/template-centos.json

build:centos:
    stage: 'build'
    script:
        - docker login --username amine7777 --password $DOCKER_ACCESS_TOKEN
        - packer build templates/docker/template-centos.json
    only:
        changes:
            - scripts/centos.sh
            - templates/docker/template-centos.json

########## UBUNTU
validate:ubuntu:
    stage: 'validate'
    script:
        - packer validate templates/docker/template-ubuntu.json
    only:
        changes:
            - scripts/ubuntu.sh
            - templates/docker/template-ubuntu.json

build:ubuntu:
    stage: 'build'
    script:
        - docker login --username amine7777 --password $DOCKER_ACCESS_TOKEN
        - packer build templates/docker/template-ubuntu.json
    only:
        changes:
            - scripts/ubuntu.sh
            - templates/docker/template-ubuntu.json

########## ALPINE
validate:alpine:
    stage: 'validate'
    script:
        - packer validate templates/docker/template-alpine.json
    only:
        changes:
            - scripts/alpine.sh
            - templates/docker/template-alpine.json

build:alpine:
    stage: 'build'
    script:
        - docker login --username amine7777 --password $DOCKER_ACCESS_TOKEN
        - packer build templates/docker/template-alpine.json
    only:
        changes:
            - scripts/alpine.sh
            - templates/docker/template-alpine.json
