---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    strategy:
      matrix:
        os_name:
          - centos8
          - centos7
          # - debian10
          # - ubuntu2004
          # - ubuntu1804
          # - fedora32
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: templates/docker/test.json 
        env:
          PLAYBOOK: ansible
          ANSIBLE_FORCE_COLOR: '1'
          OS_NAME: ${{ matrix.os_name }}

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install docker

      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -debug"
          target: templates/docker/test.json
        env:
          PLAYBOOK: ansible
          ANSIBLE_FORCE_COLOR: '1'
          OS_NAME: ${{ matrix.os_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}