---
name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Packer build
        uses: riznob/packer-build-action@v1.1
        with:
          templateFile: 'test.json'
          varFile: 'packer-vars.json'
          workingDir: '.'