on:
  push

name: packer

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out the codebase.
      uses: actions/checkout@v2
      
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: nightly
        # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
        docker_nightly_version: snapshot-20201008

    - run: ls -la

  # validate templates
    - name: Validate Template
      uses: operatehappy/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: templates/docker/template.json

    # build artifact
    - name: Build Artifact
      uses: operatehappy/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort"
        target: templates/docker/template.json
     